#!/bin/sh

# set -x
set -e
set -u

R=$(dirname $(realpath $0))

PIO_PACKAGES=${HOME}/.platformio/packages
# FRAMEWORK_DIR=${PIO_PACKAGES}/framework-arduinoespressif8266
FRAMEWORK_DIR=${PIO_PACKAGES}/framework-arduinoespressif32


(
cat <<EOF
############################################
# Do not edit. Generated by $(basename $0)
############################################

CompileFlags:
  Add:
    - "--include-directory=${FRAMEWORK_DIR}/cores/esp8266"
    - "--include-directory=${FRAMEWORK_DIR}/tools/sdk/include"
    - "--include-directory=${FRAMEWORK_DIR}/tools/sdk/include"
EOF

(
# find ${PIO_PACKAGES}/framework-arduinoespressif32-libs/esp32 -type d -name 'include';
# esp32 variant
find ${PIO_PACKAGES}/framework-arduinoespressif32-libs/esp32s3 -type d -name 'include';
find ${PIO_PACKAGES}/framework-arduinoespressif32-libs/esp32/include/freertos/FreeRTOS-Kernel -type d -name 'include';
# Generic esp32
echo ${PIO_PACKAGES}/framework-arduinoespressif32/cores/esp32;
# Project libs
find $(realpath lib) -name '*.h' -exec dirname {} \; | sort -u | grep -v -E 'examples|test';
) | sed 's/^/    - "--include-directory=/' | sed 's/$/"/'

# find $(realpath lib) -name '*.h' -exec dirname {} \; | sort -u | grep -v -E 'examples|test' | sed 's/^/    - "--include-directory=/' | sed 's/$/"/'

cat <<EOF
Diagnostics:
  MissingIncludes: Strict
  UnusedIncludes: Strict

EOF
) | tee .clangd
